// Shared TRAJECTORIES config — imported by individual test files and run_all.mjs

const SSO = `Click "Sign in with Google". On Google page, fill email with $SVC_EMAIL, click Next. Fill password with $SVC_PASSWORD, click Next. If passkey prompt, click "Try another way" then "Enter your password". Wait 5 seconds after login.`;
const LOGIN = `Fill username/email with $SVC_EMAIL and password with $SVC_PASSWORD. Click Log In or Sign In. Wait for redirect.`;
const REG_DISCORD = `generate_identity(platform="discord"). Fill Email with $DISCORD_NEW_EMAIL. Fill "Display Name" with $DISCORD_NEW_USERNAME. Fill Username with $DISCORD_NEW_USERNAME. Fill Password with $DISCORD_NEW_PASSWORD. For Date of Birth use select_option(target="month",value="January"), select_option(target="day",value="1"), select_option(target="year",value="1995"). Click "Create Account". If captcha, solve_captcha(sitekey="auto"). If email verification, check_email(email=$DISCORD_NEW_EMAIL,sender="discord"). done(value=$DISCORD_NEW_USERNAME).`;
const REG_REDDIT = `generate_identity(platform="reddit"). Fill email with $REDDIT_NEW_EMAIL. Click Continue. If captcha, solve_captcha(sitekey="6LfirrMoAAAAAHZOipvza4kpp_VtTwLNuXVwURNQ"). check_email(email=$REDDIT_NEW_EMAIL,sender="reddit") for code. Fill code. Set username $REDDIT_NEW_USERNAME and password $REDDIT_NEW_PASSWORD. After registration if onboarding questions appear, immediately done(value=$REDDIT_NEW_USERNAME).`;
const REG_TWITTER = `generate_identity(platform="twitter"). Fill name with "Wisent User". Click Next. Fill email with $TWITTER_NEW_EMAIL. Click Next. For birthdate use select_option. Click Next. check_email(email=$TWITTER_NEW_EMAIL,sender="x.com") for code. Fill code. Set password $TWITTER_NEW_PASSWORD. done(value=$TWITTER_NEW_USERNAME).`;
const REG_TIKTOK = `generate_identity(platform="tiktok"). Click "Use phone or email". Click "Sign up with email". For birthday use select_option(target="month",value="January"), select_option(target="day",value="1"), select_option(target="year",value="1995"). Fill email with $TIKTOK_NEW_EMAIL. Fill password with $TIKTOK_NEW_PASSWORD. Click "Send code". check_email(email=$TIKTOK_NEW_EMAIL,sender="tiktok") for code. Fill code. Click Next. done(value=$TIKTOK_NEW_USERNAME).`;
const REG_INSTAGRAM = `generate_identity(platform="instagram"). Fill "Mobile Number or Email" with $INSTAGRAM_NEW_EMAIL. Fill "Full Name" with "Wisent User". Fill Username with $INSTAGRAM_NEW_USERNAME. Fill Password with $INSTAGRAM_NEW_PASSWORD. Click "Sign up". If birthday, select January 1 1995. done(value=$INSTAGRAM_NEW_USERNAME).`;

export const TRAJECTORIES = [
  { name: 'reddit_register', url: 'https://www.reddit.com/register', goal: REG_REDDIT },
  { name: 'discord_register', url: 'https://discord.com/register', goal: REG_DISCORD, waitLoad: true },
  { name: 'twitter_register', url: 'https://x.com/i/flow/signup', goal: REG_TWITTER },
  { name: 'tiktok_register', url: 'https://www.tiktok.com/signup', goal: REG_TIKTOK },
  { name: 'instagram_register', url: 'https://www.instagram.com/accounts/emailsignup/', goal: REG_INSTAGRAM },
  { name: 'reddit_login', url: 'https://www.reddit.com/login', goal: `${LOGIN} done(value="logged in").`, emailEnv: 'REDDIT_EMAIL', passEnv: 'REDDIT_PASSWORD' },
  { name: 'discord_login', url: 'https://discord.com/login', goal: `${LOGIN} done(value="logged in").`, emailEnv: 'DISCORD_EMAIL', passEnv: 'DISCORD_PASSWORD', waitLoad: true },
  { name: 'twitter_login', url: 'https://x.com/i/flow/login', goal: `Fill username/email with $SVC_EMAIL. Click Next. Fill password with $SVC_PASSWORD. Click "Log in". Wait for redirect. done(value="logged in").`, emailEnv: 'TWITTER_EMAIL', passEnv: 'TWITTER_PASSWORD' },
  { name: 'instagram_login', url: 'https://www.instagram.com/accounts/login/', goal: `fill(target="username",value=$SVC_EMAIL). fill(target="password",value=$SVC_PASSWORD). js_click(selector="button[type='submit']",text="Log in"). Wait 5 seconds. If email verification code required, check_email(email=$SVC_EMAIL,sender="instagram") for code, fill the code, click Confirm. If error "incorrect", give_up(reason="invalid credentials"). done(value="logged in").`, emailEnv: 'INSTAGRAM_EMAIL', passEnv: 'INSTAGRAM_PASSWORD' },
  { name: 'tiktok_login', url: 'https://www.tiktok.com/login/phone-or-email/email', goal: `Fill email with $SVC_EMAIL. Fill password with $SVC_PASSWORD. Click "Log in". Wait for redirect. done(value="logged in").`, emailEnv: 'TIKTOK_EMAIL', passEnv: 'TIKTOK_PASSWORD' },
  { name: 'github_login', url: 'https://github.com/login', goal: `${LOGIN} done(value="logged in").`, emailEnv: 'GITHUB_EMAIL', passEnv: 'GITHUB_PASSWORD' },
  { name: 'linkedin_register', url: 'https://www.linkedin.com/signup', goal: `generate_identity(platform="linkedin"). Fill email with $LINKEDIN_NEW_EMAIL. Click "Agree & Join". Fill password with $LINKEDIN_NEW_PASSWORD. Click "Agree & Join". Fill "first-name" with $LINKEDIN_NEW_FIRSTNAME. Fill "last-name" with $LINKEDIN_NEW_LASTNAME. Click "Continue". If captcha, solve_captcha(). If email verification, check_email(email=$LINKEDIN_NEW_EMAIL,sender="linkedin") for code, fill the code, click Submit. save_account(platform="linkedin",username=$LINKEDIN_NEW_USERNAME,email=$LINKEDIN_NEW_EMAIL,password=$LINKEDIN_NEW_PASSWORD,name=$LINKEDIN_NEW_FIRSTNAME+" "+$LINKEDIN_NEW_LASTNAME). done(value=$LINKEDIN_NEW_USERNAME).` },
  { name: 'linkedin_login', url: 'https://www.linkedin.com/login', goal: `Fill "session_key" with $SVC_EMAIL. Fill "session_password" with $SVC_PASSWORD. Click "Sign in". Wait 5 seconds. If captcha, solve_captcha(). done(value="logged in").`, emailEnv: 'LINKEDIN_EMAIL', passEnv: 'LINKEDIN_PASSWORD' },
  { name: 'oxylabs_balance', url: 'https://dashboard.oxylabs.io', goal: `${SSO} Read any traffic or balance data. done(value=<data>). Do NOT navigate().`, emailEnv: 'OXYLABS_EMAIL', passEnv: 'OXYLABS_PASSWORD' },
  { name: 'brightdata_balance', url: 'https://brightdata.com/cp', goal: `${SSO} Read any balance or credit data. done(value=<data>). Do NOT navigate().`, emailEnv: 'OXYLABS_EMAIL', passEnv: 'OXYLABS_PASSWORD' },
  { name: 'anticaptcha_balance', url: 'https://anti-captcha.com/clients', goal: `${SSO} Read any balance data. done(value=<data>). Do NOT navigate().`, emailEnv: 'OXYLABS_EMAIL', passEnv: 'OXYLABS_PASSWORD' },
  { name: 'capmonster_balance', url: 'https://dash.capmonster.cloud', goal: `${SSO} Read any balance data. done(value=<data>). Do NOT navigate().`, emailEnv: 'OXYLABS_EMAIL', passEnv: 'OXYLABS_PASSWORD' },
  { name: 'packetstream_balance', url: 'https://app.packetstream.io', goal: `${LOGIN} Read any balance or credit data. done(value=<data>).`, emailEnv: 'PACKETSTREAM_EMAIL', passEnv: 'PACKETSTREAM_PASSWORD' },
  { name: 'reddit_upvote', url: 'https://www.reddit.com/r/test', goal: `You are already logged in via cookies. Wait 3 seconds for posts to load. Use js_click(text="upvote") to upvote the first post. done(value="upvoted"). Do NOT give_up.`, emailEnv: 'REDDIT_EMAIL', passEnv: 'REDDIT_PASSWORD' },
  { name: 'reddit_comment', url: 'https://www.reddit.com/r/test/comments/18da1zl/some_test_commands/', goal: `You are already logged in via cookies. Wait 3 seconds. fill(target="join the conversation",value="Hello from weles agent"). Then js_click(text="Comment") to submit. done(value="commented"). Do NOT give_up. Do NOT navigate().`, emailEnv: 'REDDIT_EMAIL', passEnv: 'REDDIT_PASSWORD' },
  { name: 'instagram_follow', url: 'https://www.instagram.com/wisent.ai/', goal: `Wait 3 seconds. If not logged in, give_up(reason="not logged in, inject cookies"). Click "Follow" button. done(value="followed wisent.ai").`, emailEnv: 'INSTAGRAM_EMAIL', passEnv: 'INSTAGRAM_PASSWORD' },
  { name: 'instagram_like', url: 'https://www.instagram.com/wisent.ai/', goal: `Wait 3 seconds. If not logged in, give_up(reason="not logged in, inject cookies"). Click on the first post thumbnail. Wait 2 seconds. Click the heart/like button. done(value="liked").`, emailEnv: 'INSTAGRAM_EMAIL', passEnv: 'INSTAGRAM_PASSWORD' },
  { name: 'twitter_follow', url: 'https://x.com/i/flow/login', goal: `Fill username/email with $SVC_EMAIL. Click Next. Fill password with $SVC_PASSWORD. Click "Log in". Wait for redirect. navigate(url="https://x.com/elonmusk"). Wait 5 seconds. Click "Follow". done(value="followed @elonmusk").`, emailEnv: 'TWITTER_EMAIL', passEnv: 'TWITTER_PASSWORD' },
  { name: 'twitter_like', url: 'https://x.com/i/flow/login', goal: `Fill username/email with $SVC_EMAIL. Click Next. Fill password with $SVC_PASSWORD. Click "Log in". Wait for redirect. Wait 5 seconds. Find any tweet and click the heart/like button. done(value="liked").`, emailEnv: 'TWITTER_EMAIL', passEnv: 'TWITTER_PASSWORD' },
  { name: 'twitter_dm', url: 'https://x.com/i/flow/login', goal: `Fill username/email with $SVC_EMAIL. Click Next. Fill password with $SVC_PASSWORD. Click "Log in". Wait for redirect. navigate(url="https://x.com/messages"). Wait 5 seconds. Start a new message to @wisent_ai. Type "Hello from weles agent" and send. done(value="DM sent").`, emailEnv: 'TWITTER_EMAIL', passEnv: 'TWITTER_PASSWORD' },
  { name: 'tiktok_follow', url: 'https://www.tiktok.com/login/phone-or-email/email', goal: `Fill email with $SVC_EMAIL. Fill password with $SVC_PASSWORD. Click "Log in". Wait for redirect. navigate(url="https://www.tiktok.com/@tiktok"). Wait 5 seconds. Click "Follow". done(value="followed @tiktok").`, emailEnv: 'TIKTOK_EMAIL', passEnv: 'TIKTOK_PASSWORD' },
  { name: 'tiktok_like', url: 'https://www.tiktok.com/login/phone-or-email/email', goal: `Fill email with $SVC_EMAIL. Fill password with $SVC_PASSWORD. Click "Log in". Wait for redirect. Wait 5 seconds. Find any video and click the heart/like button. done(value="liked").`, emailEnv: 'TIKTOK_EMAIL', passEnv: 'TIKTOK_PASSWORD' },
  { name: 'github_star', url: 'https://github.com/login', goal: `${LOGIN} After login, navigate(url="https://github.com/anthropics/claude-code"). Wait 5 seconds. Then use js_click(text="star") to star the repo. done(value="starred").`, emailEnv: 'GITHUB_EMAIL', passEnv: 'GITHUB_PASSWORD' },
  { name: 'github_follow', url: 'https://github.com/login', goal: `${LOGIN} After login, navigate(url="https://github.com/lbartoszcze"). Wait 3 seconds. Click "Follow". done(value="followed lbartoszcze").`, emailEnv: 'GITHUB_EMAIL', passEnv: 'GITHUB_PASSWORD' },
];

export default { TRAJECTORIES };
